Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/08/2024
Var

CPC, R, D:real


Inicio

     escreval("Qual o valor de R?")
     leia(R)
     D<-R+R
     CPC<-3.1416*D
     escreva("O perímetro do círculo é ", CPC)


Fimalgoritmo