Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/08/2024
Var

CVC, R, H:real

Inicio

     escreval("Qual o valor de R?")
     leia(R)
     escreval("Qual o valor de H?")
     leia(H)
     R<-R*R
     CVC<-(3.1416*R)*H
     escreva("O perímetro do círculo é ", CVC)




Fimalgoritmo