Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/08/2024
Var

VPD, L, H:real


Inicio

      escreval("Qual o valor de L?")
      leia(L)
      escreval("Qual o valor de H?")
      leia(H)
      L<-L*L
      VPD<-L*(H/3)
      escreva("O volume da pirâmide é: ", VPD)

Fimalgoritmo