Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/08/2024
Var
R, D: real


Inicio


escreval("Qual é raio do círculo?")
leia(R)
D<- R*R
escreva("a área do círculo é = ", 3.1416*D)


Fimalgoritmo