Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/08/2024
Var
base, altura, area:real


Inicio
escreval("Qual é a base do triângulo")
leia(base)
escreval("Qual é a altura do triângulo")
leia(altura)
escreva("A área do triângulo é = ", (base*altura)/2)

Fimalgoritmo