Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/08/2024
Var
n1, n2:real


Inicio

      escreval("primeiro número")
      leia(n1)
      escreval("segundo número")
      leia(n2)
      escreva("O resultado é", (n1 - n2)/10)


Fimalgoritmo