Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/08/2024
Var

   n1, resto:real


Inicio

      escreval("Digite um número")
      leia (n1)
      resto <- n1%2
      escreva("O resto é", resto)


Fimalgoritmo