Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/08/2024
Var
VEF, R: real


Inicio
       escreval("Qual o valor de R")
       leia(R)
       R<-R*R*R
       VEF<- ((4/3)*3.1416)*R
       escreva("O volume da esfera é ",VEF)
Fimalgoritmo