Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 


Var

   n1, n2, n3, n4:inteiro
   soma:inteiro

Inicio

    n1 <- randi(10)
    n2 <- randi(10)
    n3 <- randi(10)
    n4 <- randi(10)


    escreva("será somado: ", n1, " +", n2, " +", n3, " +", n4)
    soma<- n1+n2+n3+n4

    escreval
    escreval
    escreva("O resultado da soma é: ", soma)

Fimalgoritmo
