Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 


Var

     n1, n2, percentual, soma:real

Inicio

     escreval("Digite um número.")
     leia(n1)
     escreval("Digite outro número.")
     leia(n2)

     percentual <- ((n1+n2)/100)*18.0
     soma <- percentual + (n1+n2)
     escreva("Resultado final", soma)

Fimalgoritmo