Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/08/2024
Var

   valor, percentual:real


Inicio

     escreval("Digite um número.")
     leia(valor)
     
     percentual <- (valor/100)*40.0
     escreva("Resultado final", percentual)


Fimalgoritmo